#!/bin/bash
while true; do
    cava -p ~/.config/eww/cava.ini | while IFS= read -r line; do
        line="${line%;}"
        [ -z "$line" ] && continue
        echo "[${line//;/,}]"
    done
    sleep 0.1
done
