#!/bin/bash
# Usage: popup-hover-out <window-prefix> <pin-var>
window_prefix=$1
pin=$2
if [ "$(eww get "$pin")" != "true" ]; then
    eww close "${window_prefix}-0" 2>/dev/null
    eww close "${window_prefix}-1" 2>/dev/null
fi
