# ── hyprpaper ─────────────────────────────────────────────────
# Wallpapers live in ~/Pictures/wallpapers/
# Change active wallpaper at runtime: hyprpaper-set

ipc = on
splash = false

# preload all wallpapers you want to use
# preload = /home/eqzotiqqq/my_projects/dotfiles/assets/bsod.png

# wallpaper = <monitor>,<path>   (empty monitor = all)
wallpaper = ,/home/eqzotiqqq/my_projects/dotfiles/assets/bsod.png
